name: Jest Tests

on:
  push:
    branches:
      - main # Adjust branch name if needed

jobs:
  Unit Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
